retrying failed action with response code: 500 (

```
{
    "type"=>"translog_exception", 
    "reason"=>"Failed to write operation [NoOp{seqNo=0, primaryTerm=1, reason='null'}]", 
    "index_uuid"=>"7F45S8hDTdKxM9ouJu00fg", 
    "shard"=>"1", 
    "index"=>"db_super_desk_v20180411", 
    "caused_by"=>{
        "type"=>"null_pointer_exception", 
        "reason"=>nil
    }
}
```
)
